from typing import List, Optional, Any
from pydantic import BaseModel, Field
from datetime import datetime

class NewsItem(BaseModel):
    """Represents a single news item found during search."""
    title: str
    url: str
    source: str
    date: str = Field(description="YYYY-MM-DD format")
    summary: str = ""
    recommend_comment: str = ""
    relevance_score: float = 0.0
    body: Optional[str] = None  # Full content or snippet
    
class SearchTask(BaseModel):
    """Represents a specific search task generated by the planner."""
    source: str
    query: str
    tbs: Optional[str] = None  # time range for Google/DDG
    count: int = 5
    
class NewsReport(BaseModel):
    """Represents the final news report ready for rendering."""
    topic: str
    prologue: str
    top_news: List[NewsItem]
    generated_at: str = Field(default_factory=lambda: datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

class SearchConfig(BaseModel):
    total_news: int = 50
    min_per_core_source: int = 3
    timeout: int = 60
    proxy: Optional[str] = None
    
class LLMConfig(BaseModel):
    api_key: Optional[str] = None
    base_url: Optional[str] = None
    model_name: str = "qwen-max"
    
class AppConfig(BaseModel):
    """Global Application Configuration."""
    llm: LLMConfig = Field(default_factory=LLMConfig)
    search: SearchConfig = Field(default_factory=SearchConfig)
    news_sources: Any = None # Keep flexible for now or define strictly later
